# Generated by Django 6.1 on 2026-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='user_images', verbose_name='Фото користувача'),
        ),
    ]
