# Generated by Django 6.1 on 2026-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('full', 'Повний пакет'), ('free', 'Безкоштовний пакет')], default='free', max_length=20),
        ),
    ]
