# Generated by Django 6.1 on 2026-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(default='full', max_length=50, verbose_name='Тариф'),
        ),
    ]
