# Generated by Django 6.1 on 2026-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Унікальна назва курсу')),
                ('title', models.CharField(max_length=120, verbose_name='Назва курса')),
                ('description', models.TextField(verbose_name='Опис курсу')),
                ('image', models.ImageField(default='default.png', upload_to='courses_images', verbose_name='Зображення')),
            ],
        ),
    ]
